import {Link} from 'react-router-dom'
export default function Airbnb(){return <div>
<section style={{background:'var(--primary)',color:'white'}}><div className="max-w-7xl mx-auto px-6 py-20 grid lg:grid-cols-2 gap-12 items-center">
<div><p className="text-xs tracking-widest uppercase" style={{color:'var(--accent)'}}>AIRBNB & SHORT-LETS</p>
<h1 className="text-5xl md:text-6xl mt-4 leading-tight" style={{fontFamily:'var(--font-display)'}}>Make the photos you already have work harder.</h1>
<p className="text-white/65 mt-6 text-lg leading-relaxed">Remote property presentation for Airbnb hosts, serviced-accommodation operators and short-let management companies. Upload your existing listing photos for digital decluttering, virtual staging and listing descriptions.</p>
<div className="flex flex-wrap gap-3 mt-8"><Link to="/upload" className="px-6 py-4 text-xs uppercase tracking-widest" style={{background:'var(--accent)',color:'var(--accent-foreground)'}}>Upload an Airbnb property</Link><Link to="/before-after" className="px-6 py-4 border border-white/30 text-xs uppercase tracking-widest">See before & after</Link></div></div>
<div className="p-8 border border-white/15"><p className="text-xs tracking-widest uppercase" style={{color:'var(--accent)'}}>WHY HOSTS USE IT</p>
<div className="mt-6 space-y-6"><div><h3 className="text-xl">Refresh a listing without a reshoot</h3><p className="text-white/55 text-sm mt-2">Use suitable photos you already have rather than organising another property visit.</p></div><div><h3 className="text-xl">Present rooms more clearly</h3><p className="text-white/55 text-sm mt-2">Reduce appropriate visual clutter or demonstrate the potential of a suitable empty room.</p></div><div><h3 className="text-xl">Keep portfolios consistent</h3><p className="text-white/55 text-sm mt-2">Useful for hosts and managers working across multiple apartments or short-let properties.</p></div></div></div>
</div></section>
<section className="max-w-7xl mx-auto px-6 py-20"><p className="text-xs tracking-widest uppercase" style={{color:'var(--accent)'}}>SERVICES FOR HOSTS</p><h2 className="text-4xl mt-3" style={{fontFamily:'var(--font-display)'}}>One upload. Choose what the listing needs.</h2>
<div className="grid md:grid-cols-3 gap-5 mt-9"><div className="p-7 border"><h3 className="text-xl">Digital Decluttering</h3><p className="text-3xl mt-3" style={{fontFamily:'var(--font-display)'}}>£20</p><p className="text-sm text-black/55 mt-3">per property</p></div><div className="p-7 border"><h3 className="text-xl">Virtual Staging</h3><p className="text-3xl mt-3" style={{fontFamily:'var(--font-display)'}}>£50</p><p className="text-sm text-black/55 mt-3">per property</p></div><div className="p-7 border"><h3 className="text-xl">Listing Description</h3><p className="text-3xl mt-3" style={{fontFamily:'var(--font-display)'}}>£20</p><p className="text-sm text-black/55 mt-3">per property</p></div></div>
<div className="mt-16 grid md:grid-cols-2 gap-6"><div className="p-8 border"><p className="text-xs tracking-widest uppercase" style={{color:'var(--accent)'}}>REGULAR HOSTS & OPERATORS</p><h2 className="text-3xl mt-3" style={{fontFamily:'var(--font-display)'}}>Monthly rates from £18 to £14 per property.</h2><p className="text-sm text-black/60 mt-4">Portfolio plans for professional hosts and short-let operators processing 5–20 properties per month.</p><Link to="/pricing" className="inline-block mt-6 text-xs uppercase tracking-widest">View monthly plans →</Link></div>
<div className="p-8" style={{background:'var(--primary)',color:'white'}}><p className="text-xs tracking-widest uppercase" style={{color:'var(--accent)'}}>21+ PROPERTIES / MONTH</p><h2 className="text-3xl mt-3" style={{fontFamily:'var(--font-display)'}}>Managing a larger short-let portfolio?</h2><p className="text-sm text-white/60 mt-4">Ask about a tailored Volume Account for Airbnb management companies and larger portfolios.</p><Link to="/upload" className="inline-block mt-6 text-xs uppercase tracking-widest" style={{color:'var(--accent)'}}>Talk to us about volume →</Link></div></div>
</section></div>}