import {Link} from 'react-router-dom'
const portfolio=[{src:'/portfolio/declutter-loft.png',tag:'DIGITAL DECLUTTERING'},{src:'/portfolio/stage-living.png',tag:'VIRTUAL STAGING'},{src:'/portfolio/declutter-bedroom.png',tag:'DIGITAL DECLUTTERING'},{src:'/portfolio/declutter-office.png',tag:'DIGITAL DECLUTTERING'}]
export default function Home(){return <div className="site-home"><section className="hero-classic"><div className="hero-classic-image"><img src="/portfolio/declutter-living.png" alt="Property before and after digital decluttering"/></div><div className="hero-classic-shade"/><div className="shell hero-classic-content"><div className="hero-classic-copy"><div className="eyebrow hero-classic-eyebrow">MOVEIN MEDIA · REMOTE PROPERTY PRESENTATION</div><h1>Don’t reshoot it.<br/><em>Transform it.</em></h1><p>Turn the property photos you already have into cleaner, more presentable, listing-ready marketing — without arranging another visit.</p><div className="hero-classic-actions"><Link className="btn-gold" to="/upload">Upload a property</Link><Link className="btn-hero-outline" to="/before-after">See before & after</Link></div></div></div><div className="hero-feature-bar"><div className="shell"><span>£20 decluttering</span><span>£50 virtual staging</span><span>£20 descriptions</span><span>Agency rates from £14/property</span></div></div></section>
<section className="intro-band"><div className="shell intro-grid"><div><div className="eyebrow">THE PROBLEM WE SOLVE</div><h2>Not every property is ready for its listing photos.</h2></div><p>Clutter, empty rooms and rushed marketing can make otherwise good property photography harder to use. MoveIn Media turns the images you already have into polished marketing assets, without sending someone back to the property.</p></div></section>
<section className="benefits-section"><div className="shell"><div className="section-head"><div><div className="eyebrow">WHY MOVEIN MEDIA</div><h2>Less chasing. Less rework.<br/>A better-presented listing.</h2></div><p className="benefits-lead">A managed property-presentation service for estate agents, Airbnb hosts and short-let operators who need better listing assets without another property visit.</p></div><div className="benefit-grid">
<article><strong>01</strong><h3>Avoid another property visit</h3><p>Already have usable photographs? Upload them instead of coordinating another visit with vendors, tenants or photographers.</p></article>
<article><strong>02</strong><h3>Make difficult rooms presentable</h3><p>Remove appropriate movable clutter or show the potential of suitable empty rooms with virtual staging.</p></article>
<article><strong>03</strong><h3>Save admin time</h3><p>Send the property once and let MoveIn Media handle the selected editing and marketing description.</p></article>
<article><strong>04</strong><h3>Keep marketing consistent</h3><p>Give every sale, letting or short-let listing a cleaner, more considered and consistent presentation.</p></article>
</div></div></section>
<section className="workflow-compare"><div className="shell"><div className="eyebrow">A SIMPLER WORKFLOW</div><h2>From existing photos to listing-ready assets.</h2><div className="workflow-grid"><div className="workflow-old"><small>WITHOUT MOVEIN MEDIA</small><p>Property needs work <b>→</b> chase preparation <b>→</b> arrange another visit <b>→</b> retake or edit <b>→</b> write copy <b>→</b> publish</p></div><div className="workflow-new"><small>WITH MOVEIN MEDIA</small><p><b>Upload property</b> <span>→</span> choose services <span>→</span> receive finished assets</p></div></div></div></section>
<section className="services-new shell"><div className="section-head"><div><div className="eyebrow">PAY AS YOU GO</div><h2>Only pay for what the property needs.</h2></div></div><div className="service-grid-new"><Link to="/upload" className="service-card-new dark"><span>£20</span><h3>Digital decluttering</h3><p>Remove appropriate movable clutter from the property's existing photographs.</p><b>Upload property →</b></Link><Link to="/upload" className="service-card-new"><span>£50</span><h3>Virtual staging</h3><p>Present suitable empty rooms with realistic virtual furniture while preserving the underlying space.</p><b>Upload property →</b></Link><Link to="/upload" className="service-card-new gold"><span>£20</span><h3>Property description</h3><p>Listing-ready marketing copy written from the verified property information you provide.</p><b>Order description →</b></Link></div></section>
<section className="portfolio-new"><div className="shell"><div className="section-head split"><div><div className="eyebrow light">REAL TRANSFORMATIONS</div><h2 className="white">The difference is visual.</h2></div><Link to="/before-after" className="text-link-light">View all before & after →</Link></div><div className="portfolio-grid">{portfolio.map(x=><article className="portfolio-card" key={x.src}><img src={x.src} alt={x.tag}/><div className="portfolio-caption"><small>{x.tag}</small></div></article>)}</div></div></section>
<section className="agency-value"><div className="shell agency-value-grid"><div><div className="eyebrow light">BUILT FOR REPEAT PROPERTY MARKETING</div><h2>More properties.<br/>Better monthly rates.</h2><p>Estate agencies, professional hosts and short-let operators can upload properties as they come in. Monthly plans reduce the included rate as your property volume grows.</p><Link className="btn-gold" to="/pricing">See monthly plans</Link></div><div className="rate-stack"><div><span>AGENCY 5</span><strong>£18</strong><small>per property · £90/month</small></div><div><span>AGENCY 10</span><strong>£16</strong><small>per property · £160/month</small></div><div><span>AGENCY 20</span><strong>£14</strong><small>per property · £280/month</small></div></div></div></section><section className="cta-new"><div className="shell"><div><div className="eyebrow light">READY WHEN YOU ARE</div><h2>Upload your next property.</h2><p className="text-white/60 mt-3">PAYG from £20, with monthly rates reducing to £14 per included property.</p></div><div className="cta-actions"><Link className="btn-gold" to="/upload">Upload a property</Link><Link className="btn-outline-light" to="/pricing">View pricing</Link></div></div></section></div>}
