import {Link} from 'react-router-dom'
const payg=[['Digital Decluttering','£20','per property','Existing photos professionally decluttered.'],['Virtual Staging','£50','per property','Suitable empty rooms virtually furnished.'],['Property Description','£20','per property','Listing copy from verified property details.'],['Decluttering + Description','£35','per property','Save £5 when ordered together.'],['Virtual Staging + Description','£65','per property','Save £5 when ordered together.']]
const plans=[['Portfolio 5','£90','5 properties','£18/property'],['Portfolio 10','£160','10 properties','£16/property'],['Portfolio 20','£280','20 properties','£14/property']]
export default function Pricing(){return <div><section style={{background:'var(--primary)'}} className="py-24"><div className="max-w-7xl mx-auto px-6 text-center"><p className="text-xs tracking-widest uppercase mb-4" style={{color:'var(--accent)'}}>PRICING</p><h1 className="text-5xl text-white mb-4" style={{fontFamily:'var(--font-display)'}}>Simple pricing per property.</h1><p className="text-white/60">No photography appointment. Upload your existing images and choose what you need.</p></div></section><section className="max-w-7xl mx-auto px-6 py-20"><h2 className="text-3xl mb-8" style={{fontFamily:'var(--font-display)'}}>Pay as you go</h2><div className="grid md:grid-cols-3 gap-5">{payg.map(([n,p,u,d])=><div key={n} className="p-8 border flex flex-col" style={{borderColor:'var(--border)'}}><p className="text-xs uppercase tracking-widest mb-3" style={{color:'var(--accent)'}}>{n}</p><div className="text-4xl mb-1" style={{fontFamily:'var(--font-display)'}}>{p}</div><p className="text-xs mb-5 text-black/50">{u}</p><p className="text-sm text-black/60 flex-1">{d}</p><Link to="/upload" className="mt-7 py-3 px-4 text-center text-xs uppercase tracking-widest" style={{background:'var(--primary)',color:'white'}}>Upload a property</Link></div>)}</div>
<div className="mt-20 mb-8"><p className="text-xs tracking-widest uppercase" style={{color:'var(--accent)'}}>MONTHLY PORTFOLIO PLANS</p><h2 className="text-3xl mt-2" style={{fontFamily:'var(--font-display)'}}>The more properties you send, the lower your rate.</h2><p className="text-sm mt-3 text-black/60 max-w-2xl">For estate agencies, professional hosts and short-let operators. Plans include digital decluttering + property description. Virtual staging remains a £35 subscriber add-on per property.</p></div><div className="grid md:grid-cols-3 gap-5">{plans.map(([n,p,q,e])=><div key={n} className="p-8 border" style={{borderColor:'var(--border)',background:n==='Portfolio 10'?'var(--muted)':'transparent'}}><p className="text-xs uppercase tracking-widest" style={{color:'var(--accent)'}}>{n}</p><div className="text-4xl mt-4" style={{fontFamily:'var(--font-display)'}}>{p}<span className="text-sm">/month</span></div><p className="mt-3 text-sm">{q}</p><p className="text-sm text-black/50">{e}</p><ul className="text-sm mt-6 space-y-2 text-black/60"><li>✓ Digital decluttering</li><li>✓ Property description</li><li>✓ Up to 20 images/property</li><li>✓ Client dashboard & downloads</li><li>+ Virtual staging £35/property</li></ul><Link to="/upload" className="block mt-7 py-3 text-center text-xs uppercase tracking-widest" style={{background:'var(--primary)',color:'white'}}>Start with a property</Link></div>)}</div>
<div className="mt-8 grid md:grid-cols-2 gap-5">
  <div className="p-8 border" style={{borderColor:'var(--border)',background:'var(--primary)',color:'white'}}>
    <p className="text-xs uppercase tracking-widest" style={{color:'var(--accent)'}}>MORE THAN 20 PROPERTIES?</p>
    <h3 className="text-3xl mt-4" style={{fontFamily:'var(--font-display)'}}>Volume Account</h3>
    <p className="text-lg mt-2">21+ properties / month · Custom pricing</p>
    <p className="text-sm text-white/60 mt-4">For larger estate agencies, Airbnb management companies and short-let portfolios with consistent monthly volume. We’ll build a plan around your workflow and editing requirements.</p>
    <Link to="/upload" className="inline-block mt-7 py-3 px-5 text-center text-xs uppercase tracking-widest" style={{background:'var(--accent)',color:'var(--accent-foreground)'}}>Talk to us about volume</Link>
  </div>
  <div className="p-8 border" style={{borderColor:'var(--border)'}}>
    <p className="text-xs uppercase tracking-widest" style={{color:'var(--accent)'}}>NEED A FEW EXTRA?</p>
    <h3 className="text-3xl mt-4" style={{fontFamily:'var(--font-display)'}}>Go over your allowance.</h3>
    <p className="text-sm text-black/60 mt-4">Portfolio 20 clients can submit additional standard included-service properties at £14 each rather than being blocked when they reach 20. Your normal monthly allowance resets at the next billing cycle.</p>
    <p className="text-sm text-black/60 mt-4">If you regularly exceed 20 properties, ask us about a tailored Volume Account.</p>
  </div>
</div></section></div>}
